apps/measures/urls.py
from django.urls import path
from apps.measures import views

app_name = 'measures'

urlpatterns = [
    # organ_overview 当月的运营指标概览
    path('organ_overview/<str:factory_id>/', views.organ_overview, name='organ_overview'),
    # organ_card 当日的运营卡片 measures_organ_card.html
    path('organ_card/<str:factory_id>/', views.organ_card, name='organ_card'),
    # organ_table 当日每个车间的运营表格， measures_organ_table.html
    path('organ_table/<str:factory_id>/', views.organ_table, name='organ_table'),
    # organ_chart
    path('organ_chart/<str:factory_id>/', views.organ_chart, name='organ_chart'),
    path('organ_chart/<str:factory_name>/<str:metric_name>/', views.organ_chart, name='organ_chart_with_metric'),
    #
    path('organ_month_report/<str:factory_id>', views.organ_month_report, name='organ_month_report'),

    # 当日的运营日报
    path('organs_daily_report/<str:factory_name>/', views.measures_daily_report, name='measures_daily_report'),
    # 当月的运营月报
    # path('organs_monthly_report/<str:factory_name>/', views.measures_monthly_report, name='measures_monthly_report'),
    # 多角度
    # 目标线
    path('target_line/', views.target_line, name='target_line'),
    # 时间线
    path('timeline/', views.timeline, name='timeline'),
    # 客户线
    path('customer_line/', views.customer_line, name='customer_line'),
    # 设定运营单位的运营目标
    path('metric_setting/', views.metric_setting, name='metric_setting'),
    # 接受 metric_setting.html 的 POST 请求，在 metric_config.json 设置运营目标
    path('metric_config/', views.metric_config, name='metric_config'),
    # 接受 metric_setting.html 的 DELETE 请求，在 metric_config.json 删除运营指标
    path('delete_metric/<str:factory_name>/<str:workshop_name>/<str:metric_name>/', views.delete_metric, name='delete_name'),

    # measures_metric_owe_factory.html
    path('measures_metric_owe/', views.measures_metric_owe_factory, name='measures_metric_owe_factory'),
    # measures_metric_owe_workshop.html
    path('measures_metric_owe_workshop/', views.measures_metric_owe_workshop, name='measures_metric_owe_workshop'),

    # measures_workshop_daily_operation.html
    path('measures_workshop_daily_operation/<str:factory_name>/<str:workshop_name>/', views.measures_workshop_daily_operation, name='measures_workshop_daily_operation'),
    # measures_workshop_charts.html
]

operationExcellence/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    path('', views.index, name='index'),
    path('measures/', include('apps.measures.urls')),
    # path('factory/<str:factory_name>/<str:workshop_name>/', views.factory_workshop_view, name='factory-workshop'),
]

apps/measures/models.py
from django.db import models

# Create your models here.

apps/measures/views.py
import re

import numpy as np

import easy.constants as const
import easy.easyclass as ec
import easy.easyfunc as ef
import easy.json_handle as jh

import datetime as dt
import json
from urllib.parse import unquote

from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import pandas as pd
from sqlalchemy import create_engine, text

# *** 2025-6-23 ***


# 网页 measures/measures_metric_setting.html
# 浏览 metrics 清单
# 删除 metric 记录
# 设置 metric，该功能隐藏，通过清单上的 设置 按钮打开或者关闭
def metric_setting(request):
    """
    返回一个表单，需要填写工厂 车间 运营指标 运营目标， 这个表单提交后交个 metric_config.html 处理
    需要的数据包括：
    单个工厂名称 单个车间名称
    8个运营指标，8个运营指标的发生值 8个运营指标的目标值 发生值和目标值之间的判断（是否达标）达标绿色，不达标红色 8个运营指标的主要参与值
    :param request:
    :return:
    """
    local_metric_data = jh.load_json_as_dic(const.CONFIGS_DIR / 'metric_config.json')

    # 读取 organization_config.json, 并解析成 python 字典
    organ_data = jh.load_json_as_dic(const.CONFIG_ORGANIZATION)

    # 组织代码 c001 表示公司
    factory_list = ec.Organization('c001').children_names
    # 工厂的下级单位
    factory_workshops = ec.Organization.hierarchy_dic('factory')

    metrics = const.METRICS.metric_name_list()
    metrics_en = const.METRICS.metric_en_list()

    page_number = request.GET.get('page')
    paginator = Paginator(local_metric_data, 10)
    try:
        items = paginator.page(page_number)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    context = {
        'organ_data': organ_data,
        'factories': factory_list,
        'factory_workshops': factory_workshops,
        # 'factory_workshops': json.dumps(factory_workshops),
        'metrics': metrics,
        'metrics_en': metrics_en,
        'metrics_name_en_combine': zip(metrics, metrics_en),
        'items': items
    }

    context_partial = {
        'items': items
    }

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return render(request, 'measures/measures_partial_metric_setting.html', context_partial)
    else:
        return render(request, 'measures/measures_metric_setting.html', context)


# 网页 measures/measures_metric_setting.html 上的 metric 设置表单
# 接受 metric 设置表单，在 metric_config.json 文件中修改或者添加 metric
def metric_config(request):
    # 解析 HTML 通过 POST 传输的 JSON 数据
    data = json.loads(request.body)
    print(data.values())

    # data.value() 例如：dict_values(['f004', 'owe', '0.75'])
    if all(data.values()):
        organ_id = data.get('organ_id')
        metric_name = data.get('metric')
        target = data.get('target')

        engine = create_engine(const.ENGINE_OPEX)
        with engine.begin() as conn:
            sql = text(f"update organ_metric set metric_target = :target where organization = :organ_id and metric = :metric_name;")
            result = conn.execute(sql, {
                'organ_id': organ_id,
                'metric_name': metric_name,
                'target': target,
            })
            # result 是 < sqlalchemy.engine.cursor.CursorResult object at 0x00000252B6106040 >

    # 将 organ_metric 表的数据本地化到 metric_config.json
    ef.sql_to_json('organ_metric', const.CONFIG_METRIC)

    return JsonResponse({'status': 'success'})


# *** 2025-6-23 ***


def organ_overview(request, factory_id):

    engine = create_engine(const.ENGINE_OPEX)

    context = {}

    metric_en_list = const.METRICS.metric_en_list()

    # 日期
    current_date = dt.date.today()
    fd = ec.FastDate(current_date)
    year, month = fd.prior_month()
    last_month = f"{str(year)}年{str(month)}月"
    same_day_prior_month = fd.same_day_prior_month()
    fd_same_day = ec.FastDate(same_day_prior_month)
    start_date = fd_same_day.month_first_day()
    end_date = fd_same_day.month_last_day()

    context['metric_en_list'] = metric_en_list
    context['last_month'] = last_month

    factory = ec.Organization(factory_id)

    with engine.connect() as conn:
        organ_head = ec.OrganHead(factory_id)
        organ_attendance = ec.OrganAttendance(factory)

        organ_owe = ec.OrganOwe(factory, conn)
        organ_owe.run_period_values((start_date, end_date))
        organ_sam_cost = ec.OrganSamCost(factory, conn)
        organ_sam_cost.run_period_values((start_date, end_date))
        organ_lead_time = ec.OrganLeadTime(factory, conn)
        organ_lead_time.run_period_values((start_date, end_date))
        organ_rft = ec.OrganRft(factory, conn)
        organ_rft.run_period_values((start_date, end_date))
        organ_bts = ec.OrganBts(factory, conn)
        organ_bts.run_period_values((start_date, end_date))
        organ_final_rework = ec.OrganFinalRework(factory, conn)
        organ_final_rework.run_period_values((start_date, end_date))

        # OWE
        # 全员生产效率
        # owe = availability * performance * ( 1 - indirect_rate ) >> 这是第二种计算方法
        owe = organ_owe.owe
        owe_color = organ_owe.value_color(owe, 'html')
        # 工人数 直接人工数 间接人工数
        headcounts, directs, indirects = organ_head.count_head(conn)
        # 间接比
        indirect_rate = indirects / headcounts
        # 工时
        sah = organ_owe.sah
        working_hours = organ_owe.working_hours
        downtime = 3000
        planned_break = 2000
        break_time = downtime + planned_break
        available_hours = working_hours - break_time
        direct_available_hours = available_hours * (1 - indirect_rate)
        indirect_available_hours = available_hours * indirect_rate
        # 停工时长
        break_time = downtime + planned_break
        scrap = organ_owe.scrap
        outputs = organ_owe.outputs
        # 报废率
        scrap_rate = scrap / outputs
        # 线体利用率
        availability = (working_hours - downtime - planned_break) / working_hours
        # 直接生产效率
        performance = sah / direct_available_hours
        context['owe_en_name'] = organ_owe.metric_en_name
        context['owe'] = owe
        context['owe_color'] = owe_color
        context['headcounts'] = headcounts
        context['directs'] = directs
        context['indirects'] = indirects
        context['indirects_rate'] = indirect_rate
        context['working_hours'] = working_hours
        context['direct_available_hours'] = direct_available_hours
        context['indirect_available_hours'] = indirect_available_hours
        context['downtime'] = downtime
        context['planned_break'] = planned_break
        context['sah'] = sah
        context['scrap_rate'] = scrap_rate
        context['availability'] = availability
        context['performance'] = performance

        # Sam Cost
        sam_cost = organ_sam_cost.sam_cost
        sam_cost_color = organ_sam_cost.value_color(sam_cost, 'html')
        cpm = sam_cost * owe
        sah_m = organ_sam_cost.sah_m
        sah = sah_m / 60
        labor_cost = organ_sam_cost.labor_cost
        maintenance_cost = organ_sam_cost.maintenance_cost
        depreciation = organ_sam_cost.depreciation
        rent = organ_sam_cost.rent
        utility_cost = organ_sam_cost.utility_cost
        admin_cost = organ_sam_cost.admin_cost
        others = organ_sam_cost.others
        manufacturing_cost = organ_sam_cost.manufacturing_cost
        context['sam_cost'] = sam_cost
        context['sam_cost_color'] = sam_cost_color
        context['cpm'] = cpm
        context['sah'] = sah
        context['sah_m'] = sah_m
        context['labor_cost'] = labor_cost
        context['maintenance_cost'] = maintenance_cost
        context['depreciation'] = depreciation
        context['rent'] = rent
        context['utility_cost'] = utility_cost
        context['admin_cost'] = admin_cost
        context['others'] = others
        context['manufacturing_cost'] = manufacturing_cost

        # Lead Time
        lead_time = organ_lead_time.lead_time
        offer_cycle = organ_lead_time.offer_cycle
        po_cycle = organ_lead_time.po_cycle
        delivery_cycle = organ_lead_time.delivery_cycle
        workshop_production_cycle = organ_lead_time.workshop_production_cycle
        line_product_cycle = organ_lead_time.line_product_cycle
        exit_cycle = organ_lead_time.exit_cycle
        context['lead_time'] = lead_time
        context['offer_cycle'] = offer_cycle
        context['po_cycle'] = po_cycle
        context['delivery_cycle'] = delivery_cycle
        context['workshop_production_cycle'] = workshop_production_cycle
        context['line_product_cycle'] = line_product_cycle
        context['exit_cycle'] = exit_cycle

        # BTS
        bts = organ_bts.bts
        context['bts'] = bts

    return render(request, 'measures/measures_organ_overview.html', context)


# organ_card 关于工厂车间当日的 metrics
def organ_card(request, factory_id):

    # 报表日期，可以 2024-3-1 也可以是任何一天
    # WARNING： 未对非工作日进行处理
    yesterday = dt.date(2024, 5, 13)
    # 单位-工厂
    organ = ec.Organization(factory_id)
    factory_name = organ.name
    # 工厂下属的车间
    workshop_ids = organ.children_ids
    workshop_names = organ.children_names

    # 车间数据集
    workshop_dataset = []

    engine = create_engine(const.ENGINE_OPEX)

    with engine.connect() as conn:

        for workshop_id in workshop_ids:
            # 单位 - 车间
            organ_workshop = ec.OrganHead(workshop_id)
            workshop_name = organ_workshop.name
            headcounts, directs, indirects = organ_workshop.count_head(conn)
            # indirects = headcounts - directs

            cxt = {
                'factory': factory_name,
                'workshop': workshop_name,
                'start_date': yesterday,
                'end_date': yesterday,
            }

            # OWE
            # 和 metric 相关，和对应的查询无关
            organ_owe = ec.OrganOwe(organ_workshop, conn)
            organ_owe.run_period_values((yesterday, yesterday))

            cxt.update({
                'owe_name_en': organ_owe.metric_en_name,

front/templates/measures/measures_metric_setting.html
{% extends 'base/ancestor_factory_workshop.html' %}

<!-- 头文件，主要是 css 文件 -->
{% block head %}{% endblock %}

<!-- 标题 -->
{% block title %}{% endblock %}

<!-- 内容 -->
{% block content %}

<!-- 设置 metric -->
<section id="metricTarget" class="content collapse" style="min-height: auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <!-- 卡片容器 -->
                <div class="card card-primary">
                    <div class="card-header py-2">
                        <h3 class="card-title"><small>运营指标设置</small></h3>
                    </div>

                    <!-- 设置运营单位运营目标的表单 -->
                    <form id="targetForm" data-factories="{{ factories }}" data-factory-workshops="{{ factory_workshops }}" data-metrics="{{ metrics }}">
                        <div class="card-body">
                            <!-- 组织代码 -->
                            <div class="form-group-sm">
                                <label for="organIdInput"><small><strong>组织代码</strong></small></label>
                                <input type="text" class="form-control form-control-sm" id="organIdInput" placeholder="请输入组织代码，例如：f001">
{#                                <select class="form-control form-control-sm" id="factorySelect">#}
{#                                    <option value="" selected disabled>请选择工厂</option>#}
{#                                    {% for factory in factories %}#}
{#                                        <option value={{ factory }}>{{ factory }}</option>#}
{#                                    {% endfor %}#}
{#                                </select>#}
                            </div>

                            <!-- 运营单位 -->
                            <div class="form-group-sm">
                                <label for="organInput"><small><strong>运营单位</strong></small></label>
                                <input type="text" class="form-control form-control-sm" id="organInput" placeholder="运营单位" disabled>
{#                                <select class="form-control form-control-sm" id="workshopSelect" disabled>#}
{#                                    <option value="" selected disabled>请先选择工厂</option>#}
{#                                </select>#}
                            </div>

                            <!-- 上级单位 -->
                            <div class="form-group-sm">
                                <label for="parentInput"><small><strong>上级单位</strong></small></label>
                                <input type="text" class="form-control form-control-sm" id="parentInput" placeholder="运营单位的上级单位" disabled>
                            </div>

                            <!-- 运营指标 -->
                            <div class="form-group-sm">
                                <label for="metricSelect"><small><strong>运营指标</strong></small></label>
                                <select class="form-control form-control-sm" id="metricSelect">
                                    <option value="" selected disabled>请选择运营指标</option>
                                    {% for metric_en, metric in metrics_name_en_combine %}
                                        <option value="{{ metric_en }}">{{ metric }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <!-- 运营目标 -->
                            <div class="form-group-sm">
                                <label for="targetInput"><small><strong>运营目标</strong></small></label>
                                <input type="number" class="form-control form-control-sm" id="targetInput" placeholder="请输入标准" step="any" min="0">
                            </div>
                        </div>

                        <!-- 提交按钮 -->
                        <div class="card-footer py-2">
                            <div class="row">
                                <div class="col-3"><button type="reset" class="btn btn-primary btn-sm"><small>重新设置</small></button></div>
                                <div class="col-3"><button type="submit" class="btn btn-primary btn-sm"><small>提交设置</small></button></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- metrics 清单 -->
<section class="content bg-light" style="min-height: auto">
    <div class="container-fluid">
        <div class="row">
            <div id="data-container" class="col-md-6 offset-md-3">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th class="text-center"><small ><strong>工厂</strong></small></th>
                            <th class="text-center"><small><strong>车间</strong></small></th>
                            <th class="text-center"><small><strong>运营指标</strong></small></th>
                            <th class="text-center"><small><strong>运营目标</strong></small></th>
                            <th class="text-center">
                                <button type="button" class="btn btn-outline-primary btn-xs web-fresh"><small>更新</small></button>
                                <button type="button" class="btn btn-outline-primary btn-xs" data-toggle="collapse" data-target="#metricTarget" aria-expanded="false" aria-controls="metricTarget">
                                    <small>设置</small>
                                </button>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for data in items %}
                            <tr>
                                <td class="text-center"><small>{{ data.factory }}</small></td>
                                <td class="text-center"><small>{{ data.workshop }}</small></td>
                                <td class="text-center"><small>{{ data.metric }}</small></td>
                                <td class="text-center"><small>{{ data.target }}</small></td>
                                <td class="text-center"><button type="button" class="btn btn-outline-danger btn-xs btn-delete"><small>删除</small></button></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <nav aria-label="Page navigation">
                    <ul class="pagination pagination-sm justify-content-sm-start">
                        {% if items.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ items.previous_page_number }}" onclick="loadPage(event, {{ items.previous_page_number }})">
                                <small>上一页</small>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1"><small>上一页</small></a>
                        </li>
                        {% endif %}
                        {% for number in items.paginator.page_range %}
                        <li class="page-item {% if items.number == number %}active{% endif %}">
                            <a class="page-link" href="?page={{ number }}" onclick="loadPage(event, {{ number }})">
                                <small>{{ number }}</small>
                            </a>
                        </li>
                        {% endfor %}
                        {% if items.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ items.next_page_number }}" onclick="loadPage(event, {{ items.next_page_number }})">
                                <small>下一页</small>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">
                                <small>下一页</small>
                            </a>
                        </li>
                        {% endif %} 
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>

<div class="position-fixed bottom-0 pt-3" style="z-index: 5; right: 0; bottom: 0">
    <div id="submitToast" class="toast" role="alert" aria-live="polite" aria-atomic="true" data-delay="2000">
        <div class="toast-header">
            <strong class="mr-auto">系统提示</strong>
            <button type="button" class="ml-2 mb-2 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
        hello world!
        </div>
    </div>
</div>
<!-- organ_data, organization_config.json的全部数据 -->
{{ organ_data|json_script:"organ-data" }}
<!-- factory_workshops 工厂的hierarchy -->
{{ factory_workshops|json_script:"factory-workshops" }}
{% endblock %}

<!-- 右侧侧边栏 控制栏 -->
{% block control-sidebar %}{% endblock %}

<!-- 文件末尾的 JavaScript 文件-->
{% block script %}
<script>
$(document).ready(function() {
    // metric 设置运营目标
    const targetForm = $('#targetForm');
    // metric 设置运营目标 组织代码输入框
    const organIdInput = $('#organIdInput');
    // metric 设置 运营指标下拉菜单
    const metricSelect = $('#metricSelect');
    // metric 设置 运营目标下拉菜单
    const targetInput = $('#targetInput');
    // 运营指标清单 更新按钮
    const webFresh = $('.web-fresh')
    // metric 清单
    const metricTable = $('.table');
    //  organ_data, organization_config.json的全部数据
    const hierarchy_dic = JSON.parse(document.getElementById('organ-data').textContent);

    // 显示 toast
    function showToast(message, type = 'info') {
        const toast = $('#submitToast');
        toast.find('.toast-body')
            .removeClass('text-success text-danger')
            .addClass(type === 'success' ? 'text-success' : 'text-danger')
            .text(message);

        const bsToast = new bootstrap.Toast(toast.get(0));
        bsToast.show();
    }

    // metric 设置运营目标 组织代码选择后
    organIdInput.change(function () {
        const organId = $(this).val();

        const organInput = $('#organInput');
        const parentInput = $('#parentInput');

        const organName = hierarchy_dic[organId]['name'];
        const parentName = hierarchy_dic[organId]['parent'];
        organInput.val(organName);
        parentInput.val(parentName);
    });

    metricSelect.change(function () {
        console.log($(this).val());
    })

    // metric 设置 表单提交处理
    targetForm.submit(function(e) {
        e.preventDefault();

        const organId = organIdInput.val();
        const metric = metricSelect.val();
        const target = targetInput.val();

        const postData = {
            organ_id: organId,
            metric: metric,
            target: target
        }

        let emptyFields = []
        if (!organId) emptyFields.push('组织代码');
        if (!metric) emptyFields.push('运营指标');
        if (!target) emptyFields.push('运营目标');

        if (emptyFields.length > 0) {
            {#const errorMsg = `${emptyFields.join('、')}${emptyFields.length > 1 ? '均' : ''}未填写`;#}
            const errorMsg = '您好，您的表单内容填写不完整！'
            showToast(errorMsg, 'warning');
            return;
        }

        $.ajax({
            url: '/measures/metric_config/',
            type: 'POST',
            data: JSON.stringify(postData),
            success: function (response) {
                if (response.status === 'success') {
                    showToast('设置保存成功！', 'success');
                } else {
                    showToast('操作失败！', 'danger');
                }
            }
        });
    });


    // metric 设置提交后，更新 metric 清单
    webFresh.click(function () {
        setTimeout(() => window.location.reload(), 500);
    });

    // metric 清单 删除行
    metricTable.on('click', '.btn-delete', function () {
        const row = $(this).closest('tr')
        const factory = row.find('td:first').text();
        const workshop = row.find('td:nth-child(2)').text();
        const metric = row.find('td:nth-child(3)').text();

        console.log(factory + ' ' + workshop + ' ' + metric)

        if (confirm(`确定要删除${factory}${workshop}的运营指标${metric}吗？`)) {
            {#const encodedFactory = encodeURIComponent(factory);#}
            {#const encodedWorkshop = encodeURIComponent(workshop);#}
            {#const encodedMetric = encodeURIComponent(metric);#}

            $.ajax({
                {#url: `/measures/delete_metric/${encodedFactory}/${encodedWorkshop}/${encodedMetric}/`,#}
                url: `/measures/delete_metric/${factory}/${workshop}/${metric}/`,
                {#method: 'DELETE',#}
                method: 'GET',
                success: function (response) {
                    row.fadeOut(300, () => {
                        row.remove();
                        {#setTimeout(() => window.location.reload(), 500);#}
                    });
                    showToast('已经删除成功！', 'success');
                },
                error: function(xhr) {
                    const msg = xhr.status === 404 ? '记录不存在' : '服务器端错误';
                    showToast(`删除失败：${msg}`, 'danger')
                }

            });
        }
    })
});

function loadPage(event, page) {
    event.preventDefault();  // 阻止默认跳转
    // 通过参数传递 page
    const url = `?page=${page}`;

    $.ajax({
        url: url,
        headers: {
            "X-Requested-With": "XMLHttpRequest"  // 标记为 Ajax 请求
        },
        success: function(data) {
            // 替换表格和分页部分
            $("#data-container").html(data);
        },
        error: function() {
            alert("加载数据失败，请重试！");
        }
    });
}
</script>
{% endblock %}

front/templates/measures/measures_target_line.html
{% extends 'base/ancestor_factory_workshop.html' %}

<!-- 头文件，主要是 css 文件 -->
{% block head %}
<style>
.shadow-sm {
    box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075) !important;
}
.table {
    font-size: 14px;
}
.table thead th {
    border-top: none;
    font-weight: 600;
    color: #495057;
    background-color: #f8f9fa;
    border-bottom: 2px solid #dee2e6;
}

</style>
{% endblock %}

<!-- 标题 -->
{% block title %}{% endblock %}

<!-- 内容 -->
{% block content %}
<section class="mt-5">
    <div class="row justify-content-center">
        <div class="col-6">
            <form id="searchForm" method="POST" action="{% url 'measures:target_line' %}">
                <div class="input-group">
                    <input type="text" class="form-control" id="metricSearch" name="wo_number" placeholder="请输入单位编号：c/f/w+3位数字，比如 f001" title="单位编号格式应为c/f/w+3位数字">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">查询</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row justify-content-center">
        <div id="errorAlert" class="col-6 alert alert-danger mt-3 d-none"></div>
    </div>
</section>
<section id="targetLineResult" class="container mt-4 d-none">
    <div class="d-flex justify-content-center align-items-center mb-4">
        <h2 class="mb-0">单位运营目标</h2>
    </div>
    <div class="card shadow-sm">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead class="thead-light">
                        <tr>
                            <th>工厂</th>
                            <th>车间</th>
                            <th>运营指标</th>
                            <th>运营目标</th>
                            <th>设置时间</th>
                        </tr>
                    </thead>
                    <tbody id="metricData">
{#                        {% for data in local_metric_data %}#}
{#                            <tr>#}
{#                                <td>{{ data.factory }}</td>#}
{#                                <td>{{ data.workshop }}</td>#}
{#                                <td>{{ data.metric_en_name }}</td>#}
{#                                <td>{{ data.metric_target }}</td>#}
{#                                <td>2025-5-15</td>#}
{#                            </tr>#}
{#                        {% endfor %}#}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

<!-- 右侧侧边栏 控制栏 -->
{% block control-sidebar %}{% endblock %}

<!-- 文件末尾的 JavaScript 文件-->
{% block script %}
<script>
$(document).ready(function () {
    $('#searchForm').on('submit', function (e) {
        e.preventDefault();

        const organId = $('#metricSearch').val().trim();
        const csrfToken = $('[name=csrfmiddlewaretoken]').val()

        $('#errorAlert').addClass('d-none');
        $('#targetLineResult').addClass('d-none');

        $.ajax({
            url: $(this).attr('action'),
            type: 'POST',
            data: {
                'organ_id': organId
                // 'csrfToken': csrfToken
            },
            success: function (response) {
                if (response.error) {
                    $('#errorAlert').removeClass('d-none').text(response.error);
                    console.log(response.error)
                    return;
                }
                $('#metricSearch').val('').blur();

                let tbody = $('#metricData');

                tbody.empty();


                const metricData = response.local_metric_data;

                $.each(metricData, function (index, item) {
                    let row = $('<tr>');

                    row.append($('<td>').text(item.factory));
                    row.append($('<td>').text(item.workshop));
                    row.append($('<td>').text(item.metric_en_name));
                    row.append($('<td>').text(item.metric_target));
                    row.append($('<td>').text('2025-5-15'));

                    tbody.append(row);

                    $('#targetLineResult').removeClass('d-none')
                })
            }
        })
    })
});
</script>
{% endblock %}